spring.application.name=ingestion-service

# Server Properties
server.port=9000

# Producer Properties
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topics
kafka.topic.logs=logs