spring.application.name=query-service

# Server Properties
server.port=9020

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5332/observability_platform
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
