spring.application.name=processing-service

# Server Properties
server.port=9010

# Consumer Properties
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group.id=logs-consumer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.observability.common.dto
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Topics
kafka.topic.logs=logs

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5332/observability_platform
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect